// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHY4cBf1e_yPEDMO7UnHGlN_3035CP5Q',
    appId: '1:497895874766:web:487436758b51430e0d309f',
    messagingSenderId: '497895874766',
    projectId: 'appgrokvending',
    authDomain: 'appgrokvending.firebaseapp.com',
    databaseURL: 'https://appgrokvending-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgrokvending.firebasestorage.app',
    measurementId: 'G-FBFKCQC6PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mtltUgiFwSHEjtbwe2HnTHlA0gkgBOY',
    appId: '1:497895874766:android:29cdffd4a98297ec0d309f',
    messagingSenderId: '497895874766',
    projectId: 'appgrokvending',
    databaseURL: 'https://appgrokvending-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgrokvending.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-Zav40AgtmXFM5lZpnOh_YO9YIRfXBc',
    appId: '1:497895874766:ios:1c38e69dac62edc80d309f',
    messagingSenderId: '497895874766',
    projectId: 'appgrokvending',
    databaseURL: 'https://appgrokvending-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgrokvending.firebasestorage.app',
    androidClientId: '497895874766-5gtmd1ngrknrccu5difqsh7h90q1o7nf.apps.googleusercontent.com',
    iosClientId: '497895874766-u9a6mh07c2l48lmj2sfdi8do9jmgutjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGrokVending',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-Zav40AgtmXFM5lZpnOh_YO9YIRfXBc',
    appId: '1:497895874766:ios:1c38e69dac62edc80d309f',
    messagingSenderId: '497895874766',
    projectId: 'appgrokvending',
    databaseURL: 'https://appgrokvending-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgrokvending.firebasestorage.app',
    androidClientId: '497895874766-5gtmd1ngrknrccu5difqsh7h90q1o7nf.apps.googleusercontent.com',
    iosClientId: '497895874766-u9a6mh07c2l48lmj2sfdi8do9jmgutjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGrokVending',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYHY4cBf1e_yPEDMO7UnHGlN_3035CP5Q',
    appId: '1:497895874766:web:58e2fc3b86b0625f0d309f',
    messagingSenderId: '497895874766',
    projectId: 'appgrokvending',
    authDomain: 'appgrokvending.firebaseapp.com',
    databaseURL: 'https://appgrokvending-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgrokvending.firebasestorage.app',
    measurementId: 'G-7MT0YN1E43',
  );
}
